### ISSUE TITLE
drush rn formats output in HTML instead of markdown --md not recognized

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/drush#193]
I've switched from using the 1.x-0.x branch of drush to 1.x-1.x but now my drush rn command has reverted back to the drupal style output. The list provided is in HTML instead of markup, and the links are to /node/XXX instead of github issues. I also tried using `--md` but got 

```
Unknown option: --md.  See `drush help release-notes` for available options. To suppress this error, add the option --strict=0.
```

Here's my setup, lmk if you see anything wrong:
```
Backdrop version         :  1.13.x-dev                                                    
 Site URI                 :  http://backdrop-core                                    
 Database driver          :  mysql                                                         
 Database hostname        :  127.0.0.1                                                     
 Database username        :  backdrop                                                      
 Database name            :  backdrop                                                      
 Backdrop bootstrap       :  Successful                                                    
 Backdrop user            :                                                                
 PHP executable           :  /Applications/MAMP/bin/php/php7.1.6/bin/php                   
 PHP configuration        :  /Applications/MAMP/bin/php/php7.1.6/conf/php.ini              
 PHP OS                   :  Darwin                                                        
 Drush script             :  /Users/jlampton/drush-8/drush.php                             
 Drush version            :  8.2.3                                                         
 Backdrop Drush           :  1.x-1.x                                                       
 Drush temp directory     :  /tmp                                                          
 Drush configuration      :                                                                
 Drush alias files        :  [...]   
 Install profile          :  standard                                                      
 Backdrop Settings File   :  ./settings.php  
```

**Comment by jenlampton** [comment]
Update: I switched back to the `0.x` branch and now `drush rn` is not working for me either. I don't think I was previously running a patched version, so my guess is that I've broken something. Advice appreciated.

I checked the codebase and see code in `grn/grn.drush.inc` for `release-notes` but when I run `drush rn help` I get the following error:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function drush_grn_release_notes(), 1 passed in /Users/jlampton/drush-8/includes/command.inc on line 422 and exactly 2 expected in /Users/jlampton/.drush/grn/grn.drush.inc:68
Stack trace:
#0 /Users/jlampton/drush-8/includes/command.inc(422): drush_grn_release_notes('help')
#1 /Users/jlampton/drush-8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#2 /Users/jlampton/drush-8/includes/command.inc(199): drush_command('help')
#3 /Users/jlampton/drush-8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#4 /Users/jlampton/drush-8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#5 /Users/jlampton/drush-8/drush.php(12): drush_main()
#6 {main}
  thrown in /Users/jlampton/.drush/grn/grn.drush.inc on line 68
Drush command terminated abnormally due to an unrecoverable error.                                           [error]
Error: Uncaught ArgumentCountError: Too few arguments to function drush_grn_release_notes(), 1 passed in
/Users/jlampton/drush-8/includes/command.inc on line 422 and exactly 2 expected in
/Users/jlampton/.drush/grn/grn.drush.inc:68
Stack trace:
#0 /Users/jlampton/drush-8/includes/command.inc(422): drush_grn_release_notes('help')
#1 /Users/jlampton/drush-8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#2 /Users/jlampton/drush-8/includes/command.inc(199): drush_command('help')
#3 /Users/jlampton/drush-8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#4 /Users/jlampton/drush-8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#5 /Users/jlampton/drush-8/drush.php(12): drush_main()
#6 {main}
  thrown in /Users/jlampton/.drush/grn/grn.drush.inc, line 68
```

**Comment by serundeputy** [comment]
you want `drush help rn` not ~~drush rn help~~

```bash
gff ~/code/drush-ops/backdrop-drush () 
└─ $ ∴ lando.dev drush help rn
Use of undefined constant DRUSH_BOOTSTRAP_BACKDROP_FULL - assumed 'DRUSH_BOOTSTRAP_BACKDROP_FULL' (this will throw an Error in a future version of PHP) libraries.drush.inc:14                                                                       [warning]
Generate release notes for a project between two Git tags.

Examples:
 drush release-notes                       Generate release notes from all commits between the two last tags                                                       
 drush rn 6.x-1.1                          Generate release notes from all commits between 6.x-1.1 (as end) and the previous tag (as start)                        
 drush rn 6.x-1.0 6.x-1.1                  Generate release notes from all commits between 6.x-1.0 and 6.x-1.1                                                     
 drush rn 6.x-1.0 6.x-1.x                  Use a branch for tag2 (6.x-1.x)                                                                                         
 drush rn 6.x-1.0 origin/6.x-1.x           If you don't have the branch locally, you might need to use "[remote-name]/[branch-name]"                               
 drush rn 6.x-1.0 6.x-1.x                  You can specify the changelog to direct issues to other issue trackers.                                                 
 --baseurl="http://community.openatrium.c                                                                                                                          
 om/node/"                                                                                                                                                         
 drush rn 6.x-1.0 6.x-1.x --changelog      Generate release notes from the commits between the two tags in the format for CHANGELOG.txt as expected by drupal.org. 
 drush rn 6.x-1.0 6.x-1.1                  Use git in /usr/local/git/bin/git, and using alias                                                                      
 --git=/usr/local/git/bin/git                                                                                                                                      
 drush rn 6.x-1.0 6.x-1.x --pretty="%s     Generate release notes using a custom pretty format string                                                              
 (%h)"                                                                                                                                                             
 drush rn 6.x-1.0 6.x-1.x --reverse        Generate release notes from the commits between the two tags in reverse order

Arguments:
 tag 1                                     The previous tag, the starting point for the log.                           
 tag 2                                     The current tag, the ending point for the log. This can be also be a branch

Options:
 --baseurl                                 Set the base url for all issue links. Defaults to github issue queue for Backdrop CMS usage. Issue number will be appended to path or replace "%s". 
 --changelog                               Display the commits in the format for release notes as expected by github.com.                                                                      
 --commit-count                            If set, output will show the number of commits between the two tags                                                                                 
 --commit-links                            Attach a link to the commit in drupalcode.org repository viewer to the end of the commit lines.                                                     
 --git=</path/to/git>                      Path to the git binary, defaults to "git"                                                                                                           
 --md                                      Display the commits in MD format                                                                                                                    
 --nouser                                  Do not try to link to user page using the /u/alias, as used in drupal.org                                                                           
 --pretty=<%s>                             pretty format of the message, see the git-log man page (section "PRETTY FORMATS")                                                                   
 --reverse                                 Display the commits from old to new instead of the default Git behavior that is new to old.

Aliases: rn, relnotes
```

here is `drush rn v1.0.0 v1.0.1` straight away:

```bash
gff ~/code/drush-ops/backdrop-drush/web (1.x) 
└─ $ ∴ lando.dev drush rn v1.0.0 v1.0.1
**Changes since v1.0.0**

* 2 Backdrop 1.0.1.
* 1 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/693">#693</a> from jenlampton/606-views-block-admin-text
* 2 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/606">#606</a>: Fixed Views block info description text references administer >> structure >> blocks.
* 5 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/704">#704</a> from quicksketch/617/clearfix-container
* 6 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/617">#617</a>: Add clearfix to l-container in 2-col layouts.
* 2 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/703">#703</a> from quicksketch/693/message_overlap
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/602">#602</a>: Fixing message overlap with breadcrumb in Chrome.
* 8 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/694">#694</a> from quicksketch/608/cache_layout_info
* 0 Merge branch '1.x' of github.com:backdrop/backdrop into 1.x
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/619">#619</a>: Line breaks lost in custom block body.
* d Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/702">#702</a> from quicksketch/615/layout_late_messages
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/597">#597</a>: Rename layout.css files to machine-name.css to allow for correct overriding.
* 6 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/615">#615</a>: Render messages just before layout rendering.
* 0 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/692">#692</a> from jenlampton/605-view-block-name
* 0 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/696">#696</a> from tarekdj/ux-menu
* 2 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/699">#699</a> from serundeputy/607/remove_mysterious_right_border
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/607">#607</a>: remove mysterious right borders on menu tabs sub-items.
* d Issue <a href="https://github.com/backdrop/backdrop-issues/issues/609">#609</a>: Hide select element when all options are removed.
* f Issue <a href="https://github.com/backdrop/backdrop-issues/issues/608">#608</a>: Add caching to layout_get_layout_info().
* 8 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/605">#605</a>: Fixed Views Block name not used in Add block list.
* 8 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/691">#691</a> from jenlampton/601-disable-user-pictures
* c Issue <a href="https://github.com/backdrop/backdrop-issues/issues/601">#601</a>: Fixed Impossible to save user picture settings.
* a Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/687">#687</a> from BWPanda/580/reword-password-reset-screen
* d Issue <a href="https://github.com/backdrop/backdrop-issues/issues/580">#580</a>: Re-word password reset form.
* 3 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/655">#655</a> from BWPanda/399/remove-new-from-admin-bar-links
* 0 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/399">#399</a>: Removed 'new' from 'Add new *' admin bar links.
* 0 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/682">#682</a> from jenlampton/589-term-permissions
* 0 Merge pull request <a href="https://github.com/backdrop/backdrop-issues/issues/683">#683</a> from quicksketch/591/admin_bar_fix
* 5 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/591">#591</a>: Fixing fatal error on admin_bar settings page.
* 5 Setting version string back post 1.0.0.
* 4 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/589">#589</a>: Taxonomy permissions should begin with vocabulary name.
```

which is html with github links.

here is `drush rn v1.0.0 v1.0.1 --md`:

```bash
gff ~/code/drush-ops/backdrop-drush/web (1.x) 
└─ $ ∴ lando.dev drush rn v1.0.0 v1.0.1 --md
**Changes since v1.0.0**

* 2 Backdrop 1.0.1.
* 1 Merge pull request [#693](https://github.com/backdrop/backdrop-issues/issues/693) from jenlampton/606-views-block-admin-text
* 2 Issue [#606](https://github.com/backdrop/backdrop-issues/issues/606): Fixed Views block info description text references administer >> structure >> blocks.
* 5 Merge pull request [#704](https://github.com/backdrop/backdrop-issues/issues/704) from quicksketch/617/clearfix-container
* 6 Issue [#617](https://github.com/backdrop/backdrop-issues/issues/617): Add clearfix to l-container in 2-col layouts.
* 2 Merge pull request [#703](https://github.com/backdrop/backdrop-issues/issues/703) from quicksketch/693/message_overlap
* a Issue [#602](https://github.com/backdrop/backdrop-issues/issues/602): Fixing message overlap with breadcrumb in Chrome.
* 8 Merge pull request [#694](https://github.com/backdrop/backdrop-issues/issues/694) from quicksketch/608/cache_layout_info
* 0 Merge branch '1.x' of github.com:backdrop/backdrop into 1.x
* a Issue [#619](https://github.com/backdrop/backdrop-issues/issues/619): Line breaks lost in custom block body.
* d Merge pull request [#702](https://github.com/backdrop/backdrop-issues/issues/702) from quicksketch/615/layout_late_messages
* a Issue [#597](https://github.com/backdrop/backdrop-issues/issues/597): Rename layout.css files to machine-name.css to allow for correct overriding.
* 6 Issue [#615](https://github.com/backdrop/backdrop-issues/issues/615): Render messages just before layout rendering.
* 0 Merge pull request [#692](https://github.com/backdrop/backdrop-issues/issues/692) from jenlampton/605-view-block-name
* 0 Merge pull request [#696](https://github.com/backdrop/backdrop-issues/issues/696) from tarekdj/ux-menu
* 2 Merge pull request [#699](https://github.com/backdrop/backdrop-issues/issues/699) from serundeputy/607/remove_mysterious_right_border
* a Issue [#607](https://github.com/backdrop/backdrop-issues/issues/607): remove mysterious right borders on menu tabs sub-items.
* d Issue [#609](https://github.com/backdrop/backdrop-issues/issues/609): Hide select element when all options are removed.
* f Issue [#608](https://github.com/backdrop/backdrop-issues/issues/608): Add caching to layout_get_layout_info().
* 8 Issue [#605](https://github.com/backdrop/backdrop-issues/issues/605): Fixed Views Block name not used in Add block list.
* 8 Merge pull request [#691](https://github.com/backdrop/backdrop-issues/issues/691) from jenlampton/601-disable-user-pictures
* c Issue [#601](https://github.com/backdrop/backdrop-issues/issues/601): Fixed Impossible to save user picture settings.
* a Merge pull request [#687](https://github.com/backdrop/backdrop-issues/issues/687) from BWPanda/580/reword-password-reset-screen
* d Issue [#580](https://github.com/backdrop/backdrop-issues/issues/580): Re-word password reset form.
* 3 Merge pull request [#655](https://github.com/backdrop/backdrop-issues/issues/655) from BWPanda/399/remove-new-from-admin-bar-links
* 0 Issue [#399](https://github.com/backdrop/backdrop-issues/issues/399): Removed 'new' from 'Add new *' admin bar links.
* 0 Merge pull request [#682](https://github.com/backdrop/backdrop-issues/issues/682) from jenlampton/589-term-permissions
* 0 Merge pull request [#683](https://github.com/backdrop/backdrop-issues/issues/683) from quicksketch/591/admin_bar_fix
* 5 Issue [#591](https://github.com/backdrop/backdrop-issues/issues/591): Fixing fatal error on admin_bar settings page.
* 5 Setting version string back post 1.0.0.
* 4 Issue [#589](https://github.com/backdrop/backdrop-issues/issues/589): Taxonomy permissions should begin with vocabulary name.
```

which is markdown with github links.
